apiVersion: apps/v1
kind: Deployment
metadata:
  name: osu-benchmark
spec:
  replicas: 2
  selector:
    matchLabels:
      app: osu-benchmark
  template:
    metadata:
      labels:
        app: osu-benchmark
    spec:
      containers:
      - name: osu-benchmark
        image: den00/osu-benchmark-ssh
        command: ["/bin/bash", "-c", "sleep infinity"]  # I pod rimarranno in esecuzione senza fare nulla
        ports:
        - containerPort: 8080
